export const QUALITY_TIERS = {
  low: {
    bloom: false,
    particles: 0,
    fog: false,
    characterCount: 3,
    cityRingCount: 4,
    neonPaths: false,
    reflection: false,
    shadowMapEnabled: false,
    shadowMapSize: 512,
    skyDome: false,
  },
  med: {
    bloom: true,
    particles: 0.7,
    fog: true,
    characterCount: 8,
    cityRingCount: 20,
    reflection: true,
    shadowMapEnabled: true,
    shadowMapSize: 2048,
    skyDome: true,
  },
  high: {
    bloom: true,
    particles: 1,
    fog: true,
    characterCount: 12,
    cityRingCount: 30,
    reflection: true,
    shadowMapEnabled: true,
    shadowMapSize: 2048,
    skyDome: true,
  },
};
